import type { Metadata } from 'next';
import { Public_Sans } from 'next/font/google';
import { ClerkProvider } from '@clerk/nextjs';

import './globals.css';

const publicSans = Public_Sans({
	variable: '--font-public-sans',
	subsets: ['latin'],
	display: 'swap',
});

export const metadata: Metadata = {
	title: {
		default: '',
		template: '%s - Finance',
	},
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider>
			<html lang='en'>
				<body className={`${publicSans.variable}  antialiased`}>{children}</body>
			</html>
		</ClerkProvider>
	);
}
